import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

import {ReactNode} from "react";
import Link from "next/link";

export default function RootLayout({children}: Readonly<{ children: ReactNode }>) {
    return (
        <html>
        <body>
        <div> это в корневом layout -- Добро пожаловать на главную страницу ! это сайтовский сайт который классный</div>
        <div>это тоже в корневом layout и дальше слова - кликай на них чтоб перейти по страницам----
            <Link href={'/'}>Главная-----</Link>
            <Link href={'/rote1'}>----Путь1-СТРАНИЦА1</Link>
            <Link href={'/rote2'}>----Путь2-СТРАНИЦА2</Link>
        </div>
        <div>{children}</div>
        </body>
        </html>
    );
}
